/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:850be07f-904f-4a5b-b2db-76905b6f9242",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_3IZ068yNn",
    "aws_user_pools_web_client_id": "re639u32mm1cq1laigh6m765t",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://avvpykqpjjgcpaymcfth5l5fse.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-rjb2r7f5qff6bisinkm56h5pxi",
    "aws_user_files_s3_bucket": "finalmeddisp76f4f905914d42a8829a9b70cb8986e2222054-staging",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
